from __future__ import annotations

_NET = "efflux.effects.Network"
_LOGS = "efflux.effects.Logs"
_CLOCK = "efflux.effects.Clock"
_BLOCKS = "efflux.effects.Blocks"
_RANDOM = "efflux.effects.Random"
_READS_ENV = "efflux.effects.ReadsEnv"
_READS_FS = "efflux.effects.ReadsFS"
_WRITES_FS = "efflux.effects.WritesFS"
_FILESYSTEM = "efflux.effects.Filesystem"
_PROCESS = "efflux.effects.Process"
_DATABASE = "efflux.effects.Database"


def _m(*effects: str) -> frozenset[str]:
    return frozenset(effects)


# Curated starter map: callee fullname -> declared effects. Applied by default;
# user [tool.efflux.external] entries override per callee, and --no-builtins
# disables it entirely. open() maps to Filesystem because the direction depends
# on the runtime mode argument, which static analysis cannot see.
DEFAULT_EXTERNAL_MAP: dict[str, frozenset[str]] = {
    # filesystem
    "builtins.open": _m(_FILESYSTEM),
    "io.open": _m(_FILESYSTEM),
    "pathlib.Path.read_text": _m(_READS_FS),
    "pathlib.Path.read_bytes": _m(_READS_FS),
    "pathlib.Path.write_text": _m(_WRITES_FS),
    "pathlib.Path.write_bytes": _m(_WRITES_FS),
    "os.listdir": _m(_READS_FS),
    "os.scandir": _m(_READS_FS),
    "os.stat": _m(_READS_FS),
    "os.remove": _m(_WRITES_FS),
    "os.unlink": _m(_WRITES_FS),
    "os.mkdir": _m(_WRITES_FS),
    "os.makedirs": _m(_WRITES_FS),
    "os.rename": _m(_WRITES_FS),
    "os.replace": _m(_WRITES_FS),
    # environment
    "os.getenv": _m(_READS_ENV),
    "os.getenvb": _m(_READS_ENV),
    # network
    "socket.socket": _m(_NET),
    "socket.create_connection": _m(_NET),
    "urllib.request.urlopen": _m(_NET),
    "requests.api.get": _m(_NET),
    "requests.api.post": _m(_NET),
    "requests.api.put": _m(_NET),
    "requests.api.patch": _m(_NET),
    "requests.api.delete": _m(_NET),
    "requests.api.head": _m(_NET),
    "requests.api.options": _m(_NET),
    "requests.api.request": _m(_NET),
    "httpx.get": _m(_NET),
    "httpx.post": _m(_NET),
    "httpx.put": _m(_NET),
    "httpx.patch": _m(_NET),
    "httpx.delete": _m(_NET),
    "httpx.head": _m(_NET),
    "httpx.options": _m(_NET),
    "httpx.request": _m(_NET),
    # logging
    "logging.debug": _m(_LOGS),
    "logging.info": _m(_LOGS),
    "logging.warning": _m(_LOGS),
    "logging.error": _m(_LOGS),
    "logging.critical": _m(_LOGS),
    "logging.exception": _m(_LOGS),
    "logging.log": _m(_LOGS),
    "logging.Logger.debug": _m(_LOGS),
    "logging.Logger.info": _m(_LOGS),
    "logging.Logger.warning": _m(_LOGS),
    "logging.Logger.error": _m(_LOGS),
    "logging.Logger.critical": _m(_LOGS),
    "logging.Logger.exception": _m(_LOGS),
    "logging.Logger.log": _m(_LOGS),
    # time / clock
    "time.time": _m(_CLOCK),
    "time.time_ns": _m(_CLOCK),
    "time.monotonic": _m(_CLOCK),
    "time.perf_counter": _m(_CLOCK),
    "time.process_time": _m(_CLOCK),
    "time.sleep": _m(_BLOCKS),
    "datetime.datetime.now": _m(_CLOCK),
    "datetime.datetime.today": _m(_CLOCK),
    "datetime.datetime.utcnow": _m(_CLOCK),
    # randomness
    "random.random": _m(_RANDOM),
    "random.randint": _m(_RANDOM),
    "random.randrange": _m(_RANDOM),
    "random.choice": _m(_RANDOM),
    "random.choices": _m(_RANDOM),
    "random.shuffle": _m(_RANDOM),
    "random.sample": _m(_RANDOM),
    "random.uniform": _m(_RANDOM),
    "random.getrandbits": _m(_RANDOM),
    "secrets.token_bytes": _m(_RANDOM),
    "secrets.token_hex": _m(_RANDOM),
    "secrets.token_urlsafe": _m(_RANDOM),
    "secrets.choice": _m(_RANDOM),
    "secrets.randbelow": _m(_RANDOM),
    "secrets.randbits": _m(_RANDOM),
    "uuid.uuid1": _m(_RANDOM),
    "uuid.uuid4": _m(_RANDOM),
    "os.urandom": _m(_RANDOM),
    "random.betavariate": _m(_RANDOM),
    "random.expovariate": _m(_RANDOM),
    "random.gammavariate": _m(_RANDOM),
    "random.gauss": _m(_RANDOM),
    "random.lognormvariate": _m(_RANDOM),
    "random.normalvariate": _m(_RANDOM),
    "random.paretovariate": _m(_RANDOM),
    "random.triangular": _m(_RANDOM),
    "random.vonmisesvariate": _m(_RANDOM),
    "random.weibullvariate": _m(_RANDOM),
    # processes (subprocess / shell)
    "subprocess.run": _m(_PROCESS),
    "subprocess.call": _m(_PROCESS),
    "subprocess.check_call": _m(_PROCESS),
    "subprocess.check_output": _m(_PROCESS),
    "subprocess.getoutput": _m(_PROCESS),
    "subprocess.getstatusoutput": _m(_PROCESS),
    "subprocess.Popen": _m(_PROCESS),
    "os.system": _m(_PROCESS),
    "os.popen": _m(_PROCESS),
    # filesystem: pathlib.Path reads
    "pathlib.Path.open": _m(_FILESYSTEM),
    "pathlib.Path.exists": _m(_READS_FS),
    "pathlib.Path.is_file": _m(_READS_FS),
    "pathlib.Path.is_dir": _m(_READS_FS),
    "pathlib.Path.is_symlink": _m(_READS_FS),
    "pathlib.Path.iterdir": _m(_READS_FS),
    "pathlib.Path.glob": _m(_READS_FS),
    "pathlib.Path.rglob": _m(_READS_FS),
    "pathlib.Path.stat": _m(_READS_FS),
    "pathlib.Path.lstat": _m(_READS_FS),
    # filesystem: pathlib.Path writes
    "pathlib.Path.mkdir": _m(_WRITES_FS),
    "pathlib.Path.rmdir": _m(_WRITES_FS),
    "pathlib.Path.unlink": _m(_WRITES_FS),
    "pathlib.Path.rename": _m(_WRITES_FS),
    "pathlib.Path.replace": _m(_WRITES_FS),
    "pathlib.Path.touch": _m(_WRITES_FS),
    "pathlib.Path.symlink_to": _m(_WRITES_FS),
    "pathlib.Path.chmod": _m(_WRITES_FS),
    # filesystem: os.path / os.walk reads (os.path aliases resolve into genericpath/posixpath)
    "os.walk": _m(_READS_FS),
    "genericpath.exists": _m(_READS_FS),
    "genericpath.isfile": _m(_READS_FS),
    "genericpath.isdir": _m(_READS_FS),
    "genericpath.getsize": _m(_READS_FS),
    "genericpath.getmtime": _m(_READS_FS),
    "genericpath.getctime": _m(_READS_FS),
    "posixpath.islink": _m(_READS_FS),
    "ntpath.islink": _m(_READS_FS),
    # filesystem: low-level os fds
    "os.open": _m(_FILESYSTEM),
    "os.read": _m(_READS_FS),
    "os.write": _m(_WRITES_FS),
    # filesystem: shutil / tempfile
    "shutil.copy": _m(_WRITES_FS),
    "shutil.copy2": _m(_WRITES_FS),
    "shutil.copyfile": _m(_WRITES_FS),
    "shutil.copytree": _m(_WRITES_FS),
    "shutil.move": _m(_WRITES_FS),
    "shutil.rmtree": _m(_WRITES_FS),
    "shutil.make_archive": _m(_WRITES_FS),
    "tempfile.mkstemp": _m(_WRITES_FS),
    "tempfile.mkdtemp": _m(_WRITES_FS),
    "tempfile.NamedTemporaryFile": _m(_FILESYSTEM),
    "tempfile.TemporaryFile": _m(_FILESYSTEM),
    "tempfile.TemporaryDirectory": _m(_FILESYSTEM),
    # network: http / mail / ftp / dns
    "http.client.HTTPConnection": _m(_NET),
    "http.client.HTTPSConnection": _m(_NET),
    "urllib.request.urlretrieve": _m(_NET),
    "smtplib.SMTP": _m(_NET),
    "smtplib.SMTP_SSL": _m(_NET),
    "ftplib.FTP": _m(_NET),
    "ftplib.FTP_TLS": _m(_NET),
    "socket.getaddrinfo": _m(_NET),
    "socket.gethostbyname": _m(_NET),
    "socket.gethostbyname_ex": _m(_NET),
    "socket.create_server": _m(_NET),
    # clock
    "datetime.date.today": _m(_CLOCK),
    "time.monotonic_ns": _m(_CLOCK),
    "time.perf_counter_ns": _m(_CLOCK),
    "time.thread_time": _m(_CLOCK),
    "time.thread_time_ns": _m(_CLOCK),
    # blocking
    "asyncio.tasks.sleep": _m(_BLOCKS),  # asyncio.sleep re-exports from asyncio.tasks
    "threading.Event.wait": _m(_BLOCKS),
    "threading.Condition.wait": _m(_BLOCKS),
    "queue.Queue.get": _m(_BLOCKS),
    "queue.Queue.put": _m(_BLOCKS),
    # third-party data stores (best-effort; fullnames may shift between versions)
    "sqlalchemy.create_engine": _m(_DATABASE),
    "sqlalchemy.engine.Engine.connect": _m(_DATABASE),
    "sqlalchemy.engine.Connection.execute": _m(_DATABASE),
    "sqlalchemy.orm.Session.execute": _m(_DATABASE),
    "sqlalchemy.orm.Session.commit": _m(_DATABASE),
    "sqlalchemy.orm.Session.query": _m(_DATABASE),
    "psycopg.connect": _m(_DATABASE),
    "psycopg.Connection.execute": _m(_DATABASE),
    "psycopg.Cursor.execute": _m(_DATABASE),
    "psycopg2.connect": _m(_DATABASE),
    "redis.Redis.get": _m(_DATABASE),
    "redis.Redis.set": _m(_DATABASE),
    "redis.Redis.delete": _m(_DATABASE),
    "redis.Redis.hget": _m(_DATABASE),
    "redis.Redis.hset": _m(_DATABASE),
    "redis.client.Redis.execute_command": _m(_DATABASE),
    "pymongo.MongoClient": _m(_DATABASE),
    "pymongo.collection.Collection.find": _m(_DATABASE),
    "pymongo.collection.Collection.find_one": _m(_DATABASE),
    "pymongo.collection.Collection.insert_one": _m(_DATABASE),
    "pymongo.collection.Collection.update_one": _m(_DATABASE),
    "pymongo.collection.Collection.delete_one": _m(_DATABASE),
    # third-party network
    "aiohttp.ClientSession.get": _m(_NET),
    "aiohttp.ClientSession.post": _m(_NET),
    "aiohttp.ClientSession.put": _m(_NET),
    "aiohttp.ClientSession.patch": _m(_NET),
    "aiohttp.ClientSession.delete": _m(_NET),
    "aiohttp.ClientSession.request": _m(_NET),
    "boto3.client": _m(_NET),
}
